
CREATE TABLE IF NOT EXISTS eom_services (
  id INT NOT NULL AUTO_INCREMENT,
  services VARCHAR(120) NOT NULL,
  service_value VARCHAR(10) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = MyISAM DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1;
